[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32G071C8Rx with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32G431CBUx --connect-under-reset"
#runner = "probe-rs run --chip STM32G431CBUx"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"


[profile.release]
lto = true
opt-level = "z"
#opt-level = "s"
incremental = false
codegen-units = 1
debug = true

[unstable]
build-std = ["core"]

